// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiufsfcrebawiiqndwvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppdWZzZmNyZWJhd2lpcW5kd3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3OTY0OTcsImV4cCI6MjA3NjM3MjQ5N30.AJFI1YDTN45MlXuQjF9Z9tIDO-AXJm7YnLWPxg0YNfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});